---
- name: Copy autoinstall templates
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "/var/lib/cobbler/templates/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - debian.seed
    - rhel.ks

- name: Copy custom autoinstall templates
  ansible.builtin.template:
    src: templates.j2
    dest: "/var/lib/cobbler/templates/{{ item.name }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ cobbler_autoinstall_templates }}"
  loop_control:
    label: "{{ item.name }}"
  when: cobbler_autoinstall_templates | length > 0

- name: Do not configure apt repo in preseed late script
  ansible.builtin.lineinfile:
    path: /var/lib/cobbler/scripts/preseed_late_default
    state: absent
    regexp: 'late_apt_repo_config'

- name: Add snippet to create automation user in preseed late script
  ansible.builtin.lineinfile:
    path: /var/lib/cobbler/scripts/preseed_late_default
    insertbefore: 'autoinstall_done'
    line: "$SNIPPET('{{ item }}')"
    create: true
    owner: root
    group: root
    mode: '0644'
  loop:
    - create_automation_user
    - custom_post_install

- name: Configure Cobbler profiles
  cobbler_profile:
    host: "{{ cobbler_api_host }}"
    port: "{{ cobbler_api_port | default(omit) }}"
    use_ssl: "{{ cobbler_api_use_ssl | default(omit) }}"
    username: "{{ cobbler_api_username }}"
    password: "{{ cobbler_api_password }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    properties: "{{ item.properties }}"
  delegate_to: localhost
  become: false
  loop: "{{ cobbler_profiles }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configure per_profile snippets
  vars:
    _snippet_type: per_profile
    _snippet_conf: "{{ cobbler_profiles | subelements('snippets', skip_missing=True) }}"
  ansible.builtin.include_tasks:
    file: "snippets.yml"
