---
- name: Install gpg
  ansible.builtin.package:
    name: gpg

- name: Install GPG-KEY
  ansible.builtin.apt_key:
    url: "{{ cobbler_gpg_key }}"
    keyring: /etc/apt/trusted.gpg.d/cobbler.gpg

- name: Configure Cobbler repository
  ansible.builtin.template:
    src: apt_repository.j2
    dest: /etc/apt/sources.list.d/cobbler.list
    owner: root
    group: root
    mode: '0644'
  notify: Update repository cache

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
