---
- name: "Create snippets directories {{ _snippet_type }}"
  ansible.builtin.file:
    path: "/var/lib/cobbler/snippets/{{ _snippet_type }}/{{ item.1.name }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ _snippet_conf }}"
  loop_control:
    label: "Create directory /var/lib/cobbler/snippets/{{ _snippet_type }}/{{ item.1.name }}"

- name: "Copy snippets {{ _snippet_type }}"
  ansible.builtin.template:
    src: per_snippet.j2
    owner: root
    group: root
    mode: '0644'
    dest: "/var/lib/cobbler/snippets/{{ _snippet_type }}/{{ item.1.name }}/{{ item.0.name }}"
  loop: "{{ _snippet_conf }}"
  loop_control:
    label: "Install snippet /var/lib/cobbler/snippets/{{ _snippet_type }}/{{ item.1.name }}/{{ item.0.name }}"
