---
- name: Configure per_system snippets
  vars:
    _snippet_type: per_system
    _snippet_conf: "{{ cobbler_systems | subelements('snippets', skip_missing=True) }}"
  ansible.builtin.include_tasks:
    file: "snippets.yml"
