---
- name: Create per_system snippets directories
  ansible.builtin.file:
    path: "/var/lib/cobbler/snippets/per_system/{{ item.1.name }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ cobbler_systems | subelements('snippets', skip_missing=True) }}"

- name: Copy per_system snippets
  ansible.builtin.template:
    src: per_snippet.j2
    dest: "/var/lib/cobbler/snippets/per_system/{{ item.1.name }}/{{ item.0.name }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ cobbler_systems | subelements('snippets', skip_missing=True) }}"
