---
- name: Update repository cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart apache
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: Restart cobbler
  ansible.builtin.service:
    name: cobblerd
    state: restarted
  notify:
    - Wait for cobblerd to be ready
    - Run cobbler mkloaders (would need a plugin)
    - Run cobbler sync (would need a plugin)

- name: Wait for cobblerd to be ready
  ansible.builtin.wait_for:
    port: 25151
    delay: 2

- name: Run cobbler mkloaders (would need a plugin)
  ansible.builtin.command: cobbler mkloaders

- name: Run cobbler sync (would need a plugin)
  ansible.builtin.command: cobbler sync

- name: Daemon-reload dnsmasq
  ansible.builtin.systemd_service:
    name: dnsmasq.service
    daemon_reload: true
